CREATE TABLE `wod_templates` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`owner_user_id` text,
	`wod_type` text NOT NULL,
	`time_cap_s` integer,
	`description` text,
	`body` text NOT NULL,
	`is_benchmark` integer DEFAULT false NOT NULL,
	`created_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch() * 1000) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `wod_templates_global_name_uq` ON `wod_templates` (lower("name")) WHERE "wod_templates"."owner_user_id" is null;--> statement-breakpoint
CREATE UNIQUE INDEX `wod_templates_custom_name_uq` ON `wod_templates` (`owner_user_id`,lower("name")) WHERE "wod_templates"."owner_user_id" is not null;--> statement-breakpoint
CREATE INDEX `wod_templates_owner_idx` ON `wod_templates` (`owner_user_id`);--> statement-breakpoint
CREATE INDEX `wod_templates_type_idx` ON `wod_templates` (`wod_type`);--> statement-breakpoint
-- Catalog top-up: three movements that several benchmark WODs reference.
-- INSERT OR IGNORE so a manual re-run is safe (matches 0002 convention).
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_air_squat', 'Air Squat', NULL, 'bodyweight', 'squat', 'rounds_reps', 0, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_overhead_squat', 'Overhead Squat', NULL, 'barbell', 'squat', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_sit_up', 'Sit-Up', NULL, 'bodyweight', 'core', 'rounds_reps', 0, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
-- Muscle maps for the three new movements (mirrors the slice-1 seed pattern).
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_air_squat', 'glutes', 'primary');--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_air_squat', 'quads', 'primary');--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_air_squat', 'hamstrings', 'secondary');--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_air_squat', 'abs', 'stabilizer');--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_overhead_squat', 'quads', 'primary');--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_overhead_squat', 'glutes', 'primary');--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_overhead_squat', 'abs', 'primary');--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_overhead_squat', 'rear_delt', 'secondary');--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_overhead_squat', 'erectors', 'stabilizer');--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_sit_up', 'abs', 'primary');--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_sit_up', 'obliques', 'secondary');--> statement-breakpoint
-- Benchmark WOD seed (the canonical "Girls" + selected "Heroes").
-- Body shapes are validated by @rallypoint/fitness-shared's wodBodySchema
-- at the route layer; this seed is read-only and only inserted from here.
-- timeCapS on For Time WODs is conservative (advisory) — the live UI shows
-- it but doesn't force-DNF until the user hits Finish.
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_fran', 'Fran', NULL, 'for_time', 600, '21-15-9 of thrusters (43kg) and pull-ups.', '{"wodType":"for_time","rounds":1,"schemeRounds":[21,15,9],"movements":[{"exerciseId":"fx_seed_thruster","reps":1,"loadKg":43},{"exerciseId":"fx_seed_pull_up","reps":1}]}', 1, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_grace', 'Grace', NULL, 'for_time', 600, '30 clean and jerks for time at 61kg.', '{"wodType":"for_time","rounds":1,"movements":[{"exerciseId":"fx_seed_clean_and_jerk","reps":30,"loadKg":61}]}', 1, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_helen', 'Helen', NULL, 'rounds_for_time', 1800, '3 rounds for time: 400m run, 21 kettlebell swings (24kg), 12 pull-ups.', '{"wodType":"rounds_for_time","rounds":3,"movements":[{"exerciseId":"fx_seed_run","distanceM":400},{"exerciseId":"fx_seed_kettlebell_swing","reps":21,"loadKg":24},{"exerciseId":"fx_seed_pull_up","reps":12}]}', 1, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_karen', 'Karen', NULL, 'for_time', 900, '150 wall balls for time (9kg ball to 10ft target).', '{"wodType":"for_time","rounds":1,"movements":[{"exerciseId":"fx_seed_wall_ball","reps":150,"loadKg":9}]}', 1, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_annie', 'Annie', NULL, 'for_time', 600, '50-40-30-20-10 of double-unders and sit-ups.', '{"wodType":"for_time","rounds":1,"schemeRounds":[50,40,30,20,10],"movements":[{"exerciseId":"fx_seed_double_under","reps":1},{"exerciseId":"fx_seed_sit_up","reps":1}]}', 1, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_cindy', 'Cindy', NULL, 'amrap', 1200, 'AMRAP 20: 5 pull-ups, 10 push-ups, 15 air squats.', '{"wodType":"amrap","durationS":1200,"movements":[{"exerciseId":"fx_seed_pull_up","reps":5},{"exerciseId":"fx_seed_push_up","reps":10},{"exerciseId":"fx_seed_air_squat","reps":15}]}', 1, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_mary', 'Mary', NULL, 'amrap', 1200, 'AMRAP 20: 5 handstand push-ups, 10 pistols, 15 pull-ups.', '{"wodType":"amrap","durationS":1200,"movements":[{"exerciseId":"fx_seed_handstand_push_up","reps":5},{"exerciseId":"fx_seed_pistol_squat","reps":10},{"exerciseId":"fx_seed_pull_up","reps":15}]}', 1, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_diane', 'Diane', NULL, 'for_time', 600, '21-15-9 of deadlifts (102kg) and handstand push-ups.', '{"wodType":"for_time","rounds":1,"schemeRounds":[21,15,9],"movements":[{"exerciseId":"fx_seed_conventional_deadlift","reps":1,"loadKg":102},{"exerciseId":"fx_seed_handstand_push_up","reps":1}]}', 1, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_elizabeth', 'Elizabeth', NULL, 'for_time', 900, '21-15-9 of cleans (61kg) and ring dips.', '{"wodType":"for_time","rounds":1,"schemeRounds":[21,15,9],"movements":[{"exerciseId":"fx_seed_power_clean","reps":1,"loadKg":61},{"exerciseId":"fx_seed_ring_dip","reps":1}]}', 1, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_nancy', 'Nancy', NULL, 'rounds_for_time', 1800, '5 rounds for time: 400m run, 15 overhead squats (43kg).', '{"wodType":"rounds_for_time","rounds":5,"movements":[{"exerciseId":"fx_seed_run","distanceM":400},{"exerciseId":"fx_seed_overhead_squat","reps":15,"loadKg":43}]}', 1, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
-- Heroes (selected).
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_murph', 'Murph', NULL, 'for_time', 3600, 'For time: 1 mile run, 100 pull-ups, 200 push-ups, 300 air squats, 1 mile run. Partition reps as needed; classically done wearing a 9kg vest.', '{"wodType":"for_time","rounds":1,"movements":[{"exerciseId":"fx_seed_run","distanceM":1609},{"exerciseId":"fx_seed_pull_up","reps":100},{"exerciseId":"fx_seed_push_up","reps":200},{"exerciseId":"fx_seed_air_squat","reps":300},{"exerciseId":"fx_seed_run","distanceM":1609}]}', 1, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_dt', 'DT', NULL, 'rounds_for_time', 1500, '5 rounds for time: 12 deadlifts, 9 hang power cleans, 6 push jerks. All at 70kg.', '{"wodType":"rounds_for_time","rounds":5,"movements":[{"exerciseId":"fx_seed_conventional_deadlift","reps":12,"loadKg":70},{"exerciseId":"fx_seed_hang_power_clean","reps":9,"loadKg":70},{"exerciseId":"fx_seed_push_jerk","reps":6,"loadKg":70}]}', 1, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_jt', 'JT', NULL, 'for_time', 900, '21-15-9 of handstand push-ups, ring dips, push-ups.', '{"wodType":"for_time","rounds":1,"schemeRounds":[21,15,9],"movements":[{"exerciseId":"fx_seed_handstand_push_up","reps":1},{"exerciseId":"fx_seed_ring_dip","reps":1},{"exerciseId":"fx_seed_push_up","reps":1}]}', 1, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_michael', 'Michael', NULL, 'rounds_for_time', 1800, '3 rounds for time: 800m run, 50 GHD back extensions, 50 sit-ups.', '{"wodType":"rounds_for_time","rounds":3,"movements":[{"exerciseId":"fx_seed_run","distanceM":800},{"exerciseId":"fx_seed_ghd_hip_extension","reps":50},{"exerciseId":"fx_seed_sit_up","reps":50}]}', 1, (unixepoch()*1000), (unixepoch()*1000));--> statement-breakpoint
INSERT OR IGNORE INTO wod_templates (id, name, owner_user_id, wod_type, time_cap_s, description, body, is_benchmark, created_at, updated_at) VALUES ('wt_seed_kelly', 'Kelly', NULL, 'rounds_for_time', 1800, '5 rounds for time: 400m run, 30 wall balls (9kg), 30 box jumps (24in).', '{"wodType":"rounds_for_time","rounds":5,"movements":[{"exerciseId":"fx_seed_run","distanceM":400},{"exerciseId":"fx_seed_wall_ball","reps":30,"loadKg":9},{"exerciseId":"fx_seed_box_jump","reps":30}]}', 1, (unixepoch()*1000), (unixepoch()*1000));