-- Seed: global exercise catalog top-up (batch 2, 2026-07 feature batch).
-- Generated by packages/fitness-db/seed/generate.ts — do not edit by hand.
-- Re-run: npm run fitness:db:seed:gen
-- Additive and backward-compatible: inserts only, no DDL (same shape as 0012).

INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_b_stance_hip_thrust', 'B-Stance Hip Thrust', NULL, 'barbell', 'hinge', 'load_reps', 1, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_b_stance_romanian_deadlift', 'B-Stance Romanian Deadlift', NULL, 'barbell', 'hinge', 'load_reps', 1, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_back_extension', 'Back Extension', NULL, 'bodyweight', 'hinge', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_bayesian_curl', 'Bayesian Curl', NULL, 'cable', 'isolation', 'load_reps', 1, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_belt_squat', 'Belt Squat', NULL, 'machine', 'squat', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_board_press', 'Board Press', NULL, 'barbell', 'horizontal_push', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_cable_crossover', 'Cable Crossover', NULL, 'cable', 'horizontal_push', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_close_grip_bench_press', 'Close-Grip Bench Press', NULL, 'barbell', 'horizontal_push', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_copenhagen_plank', 'Copenhagen Plank', NULL, 'bodyweight', 'core', 'duration', 1, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_drag_curl', 'Drag Curl', NULL, 'barbell', 'isolation', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_dragon_flag', 'Dragon Flag', NULL, 'bodyweight', 'core', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_floor_press', 'Floor Press', NULL, 'barbell', 'horizontal_push', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_hanging_leg_raise', 'Hanging Leg Raise', NULL, 'bodyweight', 'core', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_jefferson_deadlift', 'Jefferson Deadlift', NULL, 'barbell', 'hinge', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_jm_press', 'JM Press', NULL, 'barbell', 'horizontal_push', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_kroc_row', 'Kroc Row', NULL, 'dumbbell', 'horizontal_pull', 'load_reps', 1, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_landmine_press', 'Landmine Press', NULL, 'barbell', 'vertical_push', 'load_reps', 1, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_larsen_press', 'Larsen Press', NULL, 'barbell', 'horizontal_push', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_lying_leg_curl', 'Lying Leg Curl', NULL, 'machine', 'isolation', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_meadows_row', 'Meadows Row', NULL, 'barbell', 'horizontal_pull', 'load_reps', 1, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_pause_squat', 'Pause Squat', NULL, 'barbell', 'squat', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_powell_raise', 'Powell Raise', NULL, 'dumbbell', 'isolation', 'load_reps', 1, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_reverse_curl', 'Reverse Curl', NULL, 'barbell', 'isolation', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_reverse_hyperextension', 'Reverse Hyperextension', NULL, 'machine', 'hinge', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_rope_pushdown', 'Rope Pushdown', NULL, 'cable', 'isolation', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_seal_row', 'Seal Row', NULL, 'barbell', 'horizontal_pull', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_seated_leg_curl', 'Seated Leg Curl', NULL, 'machine', 'isolation', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_single_arm_cable_pushdown', 'Single-Arm Cable Pushdown', NULL, 'cable', 'isolation', 'load_reps', 1, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_sissy_squat', 'Sissy Squat', NULL, 'bodyweight', 'squat', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_snatch_grip_deadlift', 'Snatch-Grip Deadlift', NULL, 'barbell', 'hinge', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_spoto_press', 'Spoto Press', NULL, 'barbell', 'horizontal_push', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_t_bar_row', 'T-Bar Row', NULL, 'machine', 'horizontal_pull', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_tibialis_raise', 'Tibialis Raise', NULL, 'bodyweight', 'isolation', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES ('fx_seed_y_raise', 'Y-Raise', NULL, 'dumbbell', 'isolation', 'load_reps', 0, (unixepoch()*1000), (unixepoch()*1000));
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_b_stance_hip_thrust', 'glutes', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_b_stance_hip_thrust', 'hamstrings', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_b_stance_romanian_deadlift', 'erectors', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_b_stance_romanian_deadlift', 'glutes', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_b_stance_romanian_deadlift', 'hamstrings', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_back_extension', 'erectors', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_back_extension', 'glutes', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_back_extension', 'hamstrings', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_bayesian_curl', 'biceps', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_bayesian_curl', 'forearms', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_belt_squat', 'adductors', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_belt_squat', 'glutes', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_belt_squat', 'hamstrings', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_belt_squat', 'quads', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_board_press', 'chest_lower', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_board_press', 'chest_upper', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_board_press', 'front_delt', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_board_press', 'triceps', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_cable_crossover', 'chest_lower', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_cable_crossover', 'chest_upper', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_cable_crossover', 'front_delt', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_close_grip_bench_press', 'chest_lower', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_close_grip_bench_press', 'chest_upper', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_close_grip_bench_press', 'front_delt', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_close_grip_bench_press', 'triceps', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_copenhagen_plank', 'abs', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_copenhagen_plank', 'adductors', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_copenhagen_plank', 'obliques', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_drag_curl', 'biceps', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_drag_curl', 'forearms', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_dragon_flag', 'abs', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_dragon_flag', 'lats', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_dragon_flag', 'obliques', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_floor_press', 'chest_lower', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_floor_press', 'chest_upper', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_floor_press', 'front_delt', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_floor_press', 'triceps', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_hanging_leg_raise', 'abs', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_hanging_leg_raise', 'forearms', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_hanging_leg_raise', 'obliques', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_jefferson_deadlift', 'erectors', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_jefferson_deadlift', 'glutes', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_jefferson_deadlift', 'hamstrings', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_jefferson_deadlift', 'obliques', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_jefferson_deadlift', 'quads', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_jm_press', 'chest_upper', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_jm_press', 'front_delt', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_jm_press', 'triceps', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_kroc_row', 'biceps', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_kroc_row', 'forearms', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_kroc_row', 'lats', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_kroc_row', 'rhomboids', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_kroc_row', 'traps', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_landmine_press', 'abs', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_landmine_press', 'chest_upper', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_landmine_press', 'front_delt', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_landmine_press', 'triceps', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_larsen_press', 'abs', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_larsen_press', 'chest_lower', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_larsen_press', 'chest_upper', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_larsen_press', 'front_delt', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_larsen_press', 'triceps', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_lying_leg_curl', 'calves', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_lying_leg_curl', 'hamstrings', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_meadows_row', 'biceps', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_meadows_row', 'forearms', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_meadows_row', 'lats', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_meadows_row', 'rear_delt', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_meadows_row', 'rhomboids', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_pause_squat', 'abs', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_pause_squat', 'adductors', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_pause_squat', 'erectors', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_pause_squat', 'glutes', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_pause_squat', 'hamstrings', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_pause_squat', 'quads', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_powell_raise', 'rear_delt', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_powell_raise', 'rhomboids', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_reverse_curl', 'biceps', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_reverse_curl', 'forearms', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_reverse_hyperextension', 'erectors', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_reverse_hyperextension', 'glutes', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_reverse_hyperextension', 'hamstrings', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_rope_pushdown', 'triceps', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_seal_row', 'biceps', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_seal_row', 'lats', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_seal_row', 'rear_delt', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_seal_row', 'rhomboids', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_seated_leg_curl', 'hamstrings', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_single_arm_cable_pushdown', 'triceps', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_sissy_squat', 'abs', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_sissy_squat', 'quads', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_snatch_grip_deadlift', 'erectors', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_snatch_grip_deadlift', 'forearms', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_snatch_grip_deadlift', 'glutes', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_snatch_grip_deadlift', 'hamstrings', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_snatch_grip_deadlift', 'lats', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_snatch_grip_deadlift', 'traps', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_spoto_press', 'chest_lower', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_spoto_press', 'chest_upper', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_spoto_press', 'front_delt', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_spoto_press', 'triceps', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_t_bar_row', 'biceps', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_t_bar_row', 'erectors', 'stabilizer');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_t_bar_row', 'lats', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_t_bar_row', 'rear_delt', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_t_bar_row', 'rhomboids', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_t_bar_row', 'traps', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_tibialis_raise', 'calves', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_y_raise', 'front_delt', 'secondary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_y_raise', 'side_delt', 'primary');
--> statement-breakpoint
INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES ('fx_seed_y_raise', 'traps', 'secondary');
--> statement-breakpoint