// Event slug generation. Per the product rule (#16 follow-up):
//   default slug = <slugified-name, max 24 chars>-<4 random chars>
// Custom user-chosen slugs land later as a paid-tier feature; for now
// every event slug is auto-generated by the server at create time and
// is immutable post-create.
//
// Pure helpers so events-api can call them inside its create flow and
// the test suite can exercise the math without spinning up Postgres.

// Lowercase no-ambiguous alphabet — drops 0, o, 1, l, i to keep slugs
// readable when shared verbally or pasted from screenshots. 30 chars
// × 4 positions = 810k namespace per name-prefix, so the collision-
// retry loop in events-api almost never fires in practice.
const SUFFIX_ALPHABET = '23456789abcdefghjkmnpqrstvwxyz'
const SUFFIX_LENGTH = 4

// Pre-suffix cap on the slugified name portion. Combined with the
// '-' separator + SUFFIX_LENGTH this yields a maximum slug length of
// 24 + 1 + 4 = 29 chars, comfortably under the 50-char eventSlugField
// validator ceiling and under any reasonable URL cap.
export const SLUG_NAME_MAX = 24
export const SLUG_SUFFIX_LENGTH = SUFFIX_LENGTH

// Slugify a human-typed event name into the URL-safe prefix portion.
// Lowercase, kebab-case, no leading/trailing/double hyphens, capped at
// 24 chars. Returns '' for names that slugify to nothing (e.g.
// all-punctuation, all-emoji); callers fall back to a synthesised
// `event-<suffix>` shape.
export function slugifyEventName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, SLUG_NAME_MAX)
    .replace(/-+$/g, '')
}

// Generate a `SUFFIX_LENGTH`-char random suffix from the no-ambiguous
// alphabet. The randomByte function is injected so the helper stays
// pure and testable; the events-api caller passes
// `() => crypto.randomBytes(1)[0]` (Node) at runtime.
export function generateSlugSuffix(randomByte: () => number): string {
  const out: string[] = []
  for (let i = 0; i < SUFFIX_LENGTH; i += 1) {
    out.push(SUFFIX_ALPHABET[randomByte() % SUFFIX_ALPHABET.length]!)
  }
  return out.join('')
}

// Build a full event slug: slugified-name (capped) + '-' + suffix. For
// empty-slugifying names (all-punctuation), the prefix collapses to
// `event` so the URL still reads as one. The result always matches the
// eventSlugField regex.
export function generateEventSlug(
  name: string,
  randomByte: () => number,
): string {
  const base = slugifyEventName(name) || 'event'
  return `${base}-${generateSlugSuffix(randomByte)}`
}
