#!/usr/bin/env bash
# scripts/dev.sh — one-command local dev stack for Rallypoint (Cloudflare-native).
#
# Boots all five Workers under `wrangler dev` (local D1 + R2 + Durable Objects
# via Miniflare) plus the five Vite UIs, in this terminal with prefixed logs.
# No Docker, no Postgres, no Mailpit, no MinIO — the CF migration (#313) moved
# everything onto Workers primitives:
#   • D1 (SQLite)   — local, under .wrangler/state; migrations applied below.
#   • R2            — Miniflare in-process emulator (was MinIO).
#   • Mail          — MAILER=log (the wrangler.toml default) prints every email
#                     into the [id-api] log (was Mailpit). Grab verify/reset
#                     links from there.
#
# Ctrl+C stops every server. Nothing is left running in the background.
#
# Browser:
#   http://localhost:5173   — Rallypoint ID hosted UI
#                              (use Chrome until #20 lands; Safari/Firefox
#                              silently drop __Host- cookies on http://localhost)
#   http://localhost:5174   — Rallypoint Events hosted UI
#   http://localhost:5175   — Rallypoint Lists hosted UI
#   http://localhost:5176   — Rallypoint Money hosted UI
#   http://localhost:5177   — Rallypoint Planner hosted UI
#   http://localhost:8080   — RPID API; /api/v1/health is unauthenticated
#   http://localhost:8081   — Events API; /api/v1/health is unauthenticated
#   http://localhost:8082   — Lists API; /api/v1/health is unauthenticated
#   http://localhost:8083   — Money API; /api/v1/health is unauthenticated
#   http://localhost:8084   — Planner API; /api/v1/health is unauthenticated
#
# There is no automatic demo/admin seed (the old seed runner was retired in
# #313). Create an account via the signup flow at http://localhost:5173 — under
# MAILER=log the email-verification link is printed in the [id-api] log.

set -euo pipefail

# --- self-root so the script works from anywhere -----------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$SCRIPT_DIR/.."
cd "$REPO_ROOT"

# --- arg parsing -------------------------------------------------
case "${1:-up}" in
  up)
    ;;
  help|--help|-h)
    sed -n '2,40p' "$0" | sed 's/^# \?//'
    exit 0
    ;;
  *)
    echo "Unknown command: $1" >&2
    echo "Usage: $0 [up|help]" >&2
    exit 1
    ;;
esac

# --- prerequisites ------------------------------------------------
for cmd in npm node npx curl; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "[dev.sh] missing required command: $cmd" >&2
    exit 1
  fi
done

# --- cross-app SSO secrets for id-api (.dev.vars) ----------------
# wrangler dev loads secrets from a per-app `.dev.vars` file, NOT the host
# process env — so the old `export EVENTS_API_KEY=…` approach never reached
# the Workers. The four consumer apps already fall back to dev defaults in
# their own env.ts (NODE_ENV=development), so they need nothing here. id-api
# is the exception: its `*_API_KEY` are `.optional()` and its `SSO_*_HOST`
# have no default, so cross-app SSO (mint + exchange) is dark until we give
# id-api the shared dev keys (matching the consumer DEV_*_API_KEY constants)
# and the SSO hosts. Generated idempotently; .dev.vars is gitignored.
ID_DEV_VARS="$REPO_ROOT/apps/id-api/.dev.vars"
if [[ ! -f "$ID_DEV_VARS" ]]; then
  echo "[dev.sh] writing apps/id-api/.dev.vars (shared dev SSO keys + hosts)..."
  cat > "$ID_DEV_VARS" <<'DEVVARS'
# Generated by scripts/dev.sh — local dev only, gitignored.
# Shared SSO keys must match the consumer apps' env.ts dev defaults so the
# /sdk/sso/exchange handshake authorizes; SSO_*_HOST gate code minting.
EVENTS_API_KEY=dev-events-api-key-do-not-use-in-production-32+chars
LISTS_API_KEY=dev-lists-api-key-do-not-use-in-production-32+chars
MONEY_API_KEY=dev-money-api-key-do-not-use-in-production-32+chars
PLANNER_API_KEY=dev-planner-api-key-do-not-use-in-production-32+chars
SSO_EVENTS_HOST=localhost:5174
SSO_LISTS_HOST=localhost:5175
SSO_MONEY_HOST=localhost:5176
SSO_PLANNER_HOST=localhost:5177
DEVVARS
fi

# --- local D1 migrations -----------------------------------------
# `wrangler d1 migrations apply <binding> --local` reads each app's
# migrations_dir from its wrangler.toml and applies pending files to the
# local (Miniflare) D1 under .wrangler/state. Idempotent — re-runs are no-ops.
apply_migrations() {
  local app=$1
  echo "[dev.sh] applying D1 migrations for $app..."
  ( cd "apps/$app" && npx wrangler d1 migrations apply DB --local )
}
for app in id-api events-api lists-api money-api planner-api; do
  apply_migrations "$app"
done

# --- shutdown handler --------------------------------------------
# wrangler/vite each spawn a sub-tree (npx -> node -> workerd/esbuild), so
# signalling only the top subshell leaves grandchildren alive. Walk the whole
# descendant tree and TERM each one, depth-first.
PIDS=()
kill_tree() {
  local pid=$1
  for child in $(pgrep -P "$pid" 2>/dev/null || true); do
    kill_tree "$child"
  done
  kill -TERM "$pid" 2>/dev/null || true
}
cleanup() {
  trap - INT TERM HUP EXIT
  echo ""
  echo "[dev.sh] stopping all servers..."
  # `${PIDS[@]+…}` guards the empty-array case: under `set -u`, a bare
  # "${PIDS[@]}" on an empty array is an unbound-variable error on older bash
  # (e.g. macOS 3.2 / bash <4.4), which would crash cleanup itself if the trap
  # fires before any server started.
  for pid in "${PIDS[@]+"${PIDS[@]}"}"; do
    [[ -n "$pid" ]] && kill_tree "$pid"
  done
  wait 2>/dev/null || true
}
# INT = Ctrl+C; TERM = kill/ops; HUP = terminal closed; EXIT = catch-all.
trap cleanup INT TERM HUP EXIT

# --- start a Worker (wrangler dev) on an explicit port -----------
# No wrangler.toml has a [dev] port, so pass --port (bare `wrangler dev`
# defaults to :8787 and would collide). awk + fflush() prefixes each line in
# near-real-time without holding output in pipe buffers (POSIX-portable; sed -u
# is a GNU-only extension that fails on BSD/macOS sed).
start_api() {
  local app=$1 port=$2 label=$3
  echo "[dev.sh] starting $app on :$port..."
  ( cd "apps/$app" && npx wrangler dev --port "$port" 2>&1 | awk -v p="[$label]" '{ print p " " $0; fflush() }' ) &
  PIDS+=($!)
}
start_web() {
  local app=$1 port=$2 label=$3
  echo "[dev.sh] starting $app on :$port..."
  ( cd "apps/$app" && npx vite --port "$port" --strictPort 2>&1 | awk -v p="[$label]" '{ print p " " $0; fflush() }' ) &
  PIDS+=($!)
}

start_api id-api      8080 id-api
start_api events-api  8081 events-api
start_api lists-api   8082 lists-api
start_api money-api   8083 money-api
start_api planner-api 8084 planner-api

start_web id-web      5173 id-web
start_web events-web  5174 events-web
start_web lists-web   5175 lists-web
start_web money-web   5176 money-web
start_web planner-web 5177 planner-web

# --- health-wait banner ------------------------------------------
# Poll all five API /api/v1/health endpoints each iteration (not one port at a
# time — that would burn the timeout budget sequentially on a slow boot) until
# they all answer or one global ~90s budget elapses, then print the URL table.
echo "[dev.sh] waiting for the five APIs to become healthy..."
all_apis_healthy() {
  local port
  for port in 8080 8081 8082 8083 8084; do
    curl -fsS "http://localhost:$port/api/v1/health" >/dev/null 2>&1 || return 1
  done
  return 0
}
health_tries=0
until all_apis_healthy; do
  health_tries=$((health_tries + 1))
  if (( health_tries > 180 )); then
    echo "[dev.sh] WARNING: not all APIs were healthy within ~90s (continuing — check the logs above)." >&2
    break
  fi
  sleep 0.5
done

cat <<'BANNER'

  ============================================================
   Rallypoint dev stack is up (Cloudflare-native; Ctrl+C stops)
  ============================================================
   ID       http://localhost:5173   (API :8080)
   Events   http://localhost:5174   (API :8081)
   Lists    http://localhost:5175   (API :8082)
   Money    http://localhost:5176   (API :8083)
   Planner  http://localhost:5177   (API :8084)
  ------------------------------------------------------------
   Mail -> MAILER=log: verify/reset links print in the [id-api]
   log. No demo/admin seed -- sign up at :5173 to create a user.
  ============================================================

BANNER

# Block until a server exits or the user Ctrl+C's (the trap handles teardown).
wait
