// Curated global exercise catalog for Rallypoint Fitness — slice 1.
//
// Coverage reference: yuhonas/free-exercise-db (Unlicense / public domain) was
// used as a reference for exercise naming conventions and coverage breadth.
// All muscle mappings are original assignments to our own taxonomy
// (@rallypoint/fitness-shared) — no text or data was copied from that source.
//
// ~150 curated global exercises across: Strength (barbell/dumbbell/kettlebell/
// machine/cable/bodyweight), Olympic/CrossFit (barbell olympic + gymnastics),
// Endurance (cardio), and Class/conditioning.

import type { SeedExercise } from '@rallypoint/fitness-shared'

export const SEED_EXERCISES: SeedExercise[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // STRENGTH — SQUAT PATTERN (barbell / dumbbell / bodyweight)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Back Squat',
    discipline: 'barbell',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'erectors', role: 'stabilizer' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Front Squat',
    discipline: 'barbell',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'delts', role: 'stabilizer' },
      { muscleId: 'abs', role: 'stabilizer' },
      { muscleId: 'erectors', role: 'stabilizer' },
    ],
  },
  {
    name: 'Goblet Squat',
    discipline: 'kettlebell',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Dumbbell Squat',
    discipline: 'dumbbell',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },
  {
    name: 'Bodyweight Squat',
    discipline: 'bodyweight',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },
  {
    name: 'Box Squat',
    discipline: 'barbell',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'erectors', role: 'stabilizer' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Safety Bar Squat',
    discipline: 'barbell',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'erectors', role: 'stabilizer' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Bulgarian Split Squat',
    discipline: 'dumbbell',
    movementPattern: 'lunge',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Leg Press',
    discipline: 'machine',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'secondary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },
  {
    name: 'Hack Squat',
    discipline: 'machine',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'secondary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // STRENGTH — HINGE PATTERN
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Conventional Deadlift',
    discipline: 'barbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'erectors', role: 'primary' },
      { muscleId: 'quads', role: 'secondary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'lats', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Sumo Deadlift',
    discipline: 'barbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'erectors', role: 'secondary' },
      { muscleId: 'quads', role: 'secondary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Romanian Deadlift',
    discipline: 'barbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'erectors', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Dumbbell Romanian Deadlift',
    discipline: 'dumbbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'erectors', role: 'secondary' },
    ],
  },
  {
    name: 'Single-Leg Romanian Deadlift',
    discipline: 'dumbbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'erectors', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Kettlebell Swing',
    discipline: 'kettlebell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'erectors', role: 'secondary' },
      { muscleId: 'abs', role: 'secondary' },
      { muscleId: 'delts', role: 'stabilizer' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Good Morning',
    discipline: 'barbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'erectors', role: 'primary' },
      { muscleId: 'glutes', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Hip Thrust',
    discipline: 'barbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // STRENGTH — HORIZONTAL PUSH (bench / chest)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Barbell Bench Press',
    discipline: 'barbell',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },
  {
    name: 'Incline Barbell Bench Press',
    discipline: 'barbell',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },
  {
    name: 'Dumbbell Bench Press',
    discipline: 'dumbbell',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },
  {
    name: 'Incline Dumbbell Bench Press',
    discipline: 'dumbbell',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },
  {
    name: 'Decline Dumbbell Bench Press',
    discipline: 'dumbbell',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },
  {
    name: 'Cable Chest Fly',
    discipline: 'cable',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Dumbbell Chest Fly',
    discipline: 'dumbbell',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Push-Up',
    discipline: 'bodyweight',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Machine Chest Press',
    discipline: 'machine',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },
  {
    name: 'Dip',
    discipline: 'bodyweight',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'triceps', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // STRENGTH — VERTICAL PUSH (overhead pressing)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Barbell Overhead Press',
    discipline: 'barbell',
    movementPattern: 'vertical_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Dumbbell Shoulder Press',
    discipline: 'dumbbell',
    movementPattern: 'vertical_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'traps', role: 'secondary' },
    ],
  },
  {
    name: 'Arnold Press',
    discipline: 'dumbbell',
    movementPattern: 'vertical_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },
  {
    name: 'Dumbbell Lateral Raise',
    discipline: 'dumbbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
    ],
  },
  {
    name: 'Cable Lateral Raise',
    discipline: 'cable',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
    ],
  },
  {
    name: 'Dumbbell Front Raise',
    discipline: 'dumbbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
    ],
  },
  {
    name: 'Machine Shoulder Press',
    discipline: 'machine',
    movementPattern: 'vertical_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // STRENGTH — HORIZONTAL PULL (row movements)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Barbell Bent-Over Row',
    discipline: 'barbell',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
      { muscleId: 'erectors', role: 'stabilizer' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Dumbbell Row',
    discipline: 'dumbbell',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Cable Row',
    discipline: 'cable',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
    ],
  },
  {
    name: 'Machine Row',
    discipline: 'machine',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
    ],
  },
  {
    name: 'Pendlay Row',
    discipline: 'barbell',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
      { muscleId: 'erectors', role: 'stabilizer' },
    ],
  },
  {
    name: 'Face Pull',
    discipline: 'cable',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
    ],
  },
  {
    name: 'Dumbbell Rear Delt Fly',
    discipline: 'dumbbell',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
    ],
  },
  {
    name: 'Chest-Supported Row',
    discipline: 'dumbbell',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
    ],
  },
  {
    name: 'Inverted Row',
    discipline: 'bodyweight',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // STRENGTH — VERTICAL PULL (lat/pulldown movements)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Pull-Up',
    discipline: 'bodyweight',
    movementPattern: 'vertical_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'biceps', role: 'secondary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Chin-Up',
    discipline: 'bodyweight',
    movementPattern: 'vertical_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'biceps', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Lat Pulldown',
    discipline: 'cable',
    movementPattern: 'vertical_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'biceps', role: 'secondary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Wide-Grip Lat Pulldown',
    discipline: 'cable',
    movementPattern: 'vertical_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'biceps', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'traps', role: 'secondary' },
    ],
  },
  {
    name: 'Straight-Arm Pulldown',
    discipline: 'cable',
    movementPattern: 'vertical_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // STRENGTH — LUNGE PATTERN
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Barbell Lunge',
    discipline: 'barbell',
    movementPattern: 'lunge',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Dumbbell Lunge',
    discipline: 'dumbbell',
    movementPattern: 'lunge',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },
  {
    name: 'Walking Lunge',
    discipline: 'bodyweight',
    movementPattern: 'lunge',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'calves', role: 'stabilizer' },
    ],
  },
  {
    name: 'Reverse Lunge',
    discipline: 'dumbbell',
    movementPattern: 'lunge',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },
  {
    name: 'Step-Up',
    discipline: 'dumbbell',
    movementPattern: 'lunge',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'calves', role: 'stabilizer' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // STRENGTH — CARRY
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "Farmer's Carry",
    discipline: 'kettlebell',
    movementPattern: 'carry',
    metricShape: 'distance_time',
    unilateral: false,
    muscles: [
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'forearms', role: 'primary' },
      { muscleId: 'abs', role: 'secondary' },
      { muscleId: 'quads', role: 'secondary' },
      { muscleId: 'glutes', role: 'secondary' },
    ],
  },
  {
    name: 'Single-Arm Farmer Carry',
    discipline: 'kettlebell',
    movementPattern: 'carry',
    metricShape: 'distance_time',
    unilateral: true,
    muscles: [
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'forearms', role: 'primary' },
      { muscleId: 'abs', role: 'primary' },
      { muscleId: 'obliques', role: 'secondary' },
    ],
  },
  {
    name: 'Overhead Carry',
    discipline: 'kettlebell',
    movementPattern: 'carry',
    metricShape: 'distance_time',
    unilateral: true,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
      { muscleId: 'traps', role: 'stabilizer' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // STRENGTH — ISOLATION (arms, calves)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Barbell Curl',
    discipline: 'barbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'biceps', role: 'primary' },
      { muscleId: 'forearms', role: 'secondary' },
    ],
  },
  {
    name: 'Dumbbell Curl',
    discipline: 'dumbbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'biceps', role: 'primary' },
      { muscleId: 'forearms', role: 'secondary' },
    ],
  },
  {
    name: 'Hammer Curl',
    discipline: 'dumbbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'biceps', role: 'primary' },
      { muscleId: 'forearms', role: 'primary' },
    ],
  },
  {
    name: 'Preacher Curl',
    discipline: 'barbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'biceps', role: 'primary' },
    ],
  },
  {
    name: 'Cable Curl',
    discipline: 'cable',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'biceps', role: 'primary' },
      { muscleId: 'forearms', role: 'secondary' },
    ],
  },
  {
    name: 'Tricep Pushdown',
    discipline: 'cable',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'triceps', role: 'primary' },
    ],
  },
  {
    name: 'Skull Crusher',
    discipline: 'barbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'triceps', role: 'primary' },
    ],
  },
  {
    name: 'Overhead Tricep Extension',
    discipline: 'dumbbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'triceps', role: 'primary' },
    ],
  },
  {
    name: 'Standing Calf Raise',
    discipline: 'machine',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'calves', role: 'primary' },
    ],
  },
  {
    name: 'Seated Calf Raise',
    discipline: 'machine',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'calves', role: 'primary' },
    ],
  },
  {
    name: 'Leg Curl',
    discipline: 'machine',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'calves', role: 'secondary' },
    ],
  },
  {
    name: 'Leg Extension',
    discipline: 'machine',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
    ],
  },
  {
    name: 'Cable Kickback',
    discipline: 'cable',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },
  {
    name: 'Shrug',
    discipline: 'barbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // STRENGTH — CORE
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Plank',
    discipline: 'bodyweight',
    movementPattern: 'core',
    metricShape: 'duration',
    unilateral: false,
    muscles: [
      { muscleId: 'abs', role: 'primary' },
      { muscleId: 'obliques', role: 'secondary' },
      { muscleId: 'erectors', role: 'secondary' },
    ],
  },
  {
    name: 'Side Plank',
    discipline: 'bodyweight',
    movementPattern: 'core',
    metricShape: 'duration',
    unilateral: true,
    muscles: [
      { muscleId: 'obliques', role: 'primary' },
      { muscleId: 'abs', role: 'secondary' },
    ],
  },
  {
    name: 'Ab Wheel Rollout',
    discipline: 'bodyweight',
    movementPattern: 'core',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'abs', role: 'primary' },
      { muscleId: 'obliques', role: 'secondary' },
      { muscleId: 'lats', role: 'secondary' },
    ],
  },
  {
    name: 'Cable Crunch',
    discipline: 'cable',
    movementPattern: 'core',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'abs', role: 'primary' },
      { muscleId: 'obliques', role: 'secondary' },
    ],
  },
  {
    name: 'Hanging Knee Raise',
    discipline: 'bodyweight',
    movementPattern: 'core',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'abs', role: 'primary' },
      { muscleId: 'obliques', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Russian Twist',
    discipline: 'bodyweight',
    movementPattern: 'rotation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'obliques', role: 'primary' },
      { muscleId: 'abs', role: 'secondary' },
    ],
  },
  {
    name: 'Pallof Press',
    discipline: 'cable',
    movementPattern: 'core',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'abs', role: 'primary' },
      { muscleId: 'obliques', role: 'primary' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OLYMPIC / CROSSFIT — BARBELL OLYMPIC LIFTS
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Power Clean',
    discipline: 'barbell',
    movementPattern: 'olympic',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'erectors', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Hang Power Clean',
    discipline: 'barbell',
    movementPattern: 'olympic',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'quads', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Clean and Jerk',
    discipline: 'barbell',
    movementPattern: 'olympic',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'erectors', role: 'secondary' },
    ],
  },
  {
    name: 'Power Snatch',
    discipline: 'barbell',
    movementPattern: 'olympic',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'erectors', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Snatch',
    discipline: 'barbell',
    movementPattern: 'olympic',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'erectors', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },
  {
    name: 'Push Jerk',
    discipline: 'barbell',
    movementPattern: 'olympic',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'quads', role: 'secondary' },
      { muscleId: 'glutes', role: 'secondary' },
    ],
  },
  {
    name: 'Split Jerk',
    discipline: 'barbell',
    movementPattern: 'olympic',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'quads', role: 'secondary' },
      { muscleId: 'glutes', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Thruster',
    discipline: 'barbell',
    movementPattern: 'olympic',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Dumbbell Thruster',
    discipline: 'dumbbell',
    movementPattern: 'olympic',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },
  {
    name: 'Kettlebell Clean',
    discipline: 'kettlebell',
    movementPattern: 'olympic',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'forearms', role: 'secondary' },
      { muscleId: 'traps', role: 'secondary' },
    ],
  },
  {
    name: 'Kettlebell Snatch',
    discipline: 'kettlebell',
    movementPattern: 'olympic',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'forearms', role: 'secondary' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OLYMPIC / CROSSFIT — GYMNASTICS & SKILL MOVEMENTS
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Kipping Pull-Up',
    discipline: 'gymnastics',
    movementPattern: 'vertical_pull',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'biceps', role: 'secondary' },
      { muscleId: 'abs', role: 'secondary' },
    ],
  },
  {
    name: 'Butterfly Pull-Up',
    discipline: 'gymnastics',
    movementPattern: 'vertical_pull',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'biceps', role: 'secondary' },
      { muscleId: 'abs', role: 'secondary' },
    ],
  },
  {
    name: 'Muscle-Up',
    discipline: 'gymnastics',
    movementPattern: 'vertical_pull',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'triceps', role: 'primary' },
      { muscleId: 'biceps', role: 'secondary' },
      { muscleId: 'abs', role: 'secondary' },
    ],
  },
  {
    name: 'Ring Muscle-Up',
    discipline: 'gymnastics',
    movementPattern: 'vertical_pull',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'triceps', role: 'primary' },
      { muscleId: 'biceps', role: 'secondary' },
    ],
  },
  {
    name: 'Toes-to-Bar',
    discipline: 'gymnastics',
    movementPattern: 'core',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'abs', role: 'primary' },
      { muscleId: 'obliques', role: 'secondary' },
      { muscleId: 'lats', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Knees-to-Elbows',
    discipline: 'gymnastics',
    movementPattern: 'core',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'abs', role: 'primary' },
      { muscleId: 'obliques', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Handstand Push-Up',
    discipline: 'gymnastics',
    movementPattern: 'vertical_push',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Handstand Walk',
    discipline: 'gymnastics',
    movementPattern: 'other',
    metricShape: 'distance_time',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Ring Dip',
    discipline: 'gymnastics',
    movementPattern: 'horizontal_push',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'triceps', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Box Jump',
    discipline: 'bodyweight',
    movementPattern: 'other',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'calves', role: 'secondary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },
  {
    name: 'Wall Ball',
    discipline: 'bodyweight',
    movementPattern: 'squat',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },
  {
    name: 'Burpee',
    discipline: 'bodyweight',
    movementPattern: 'other',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'chest', role: 'secondary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'glutes', role: 'secondary' },
      { muscleId: 'abs', role: 'secondary' },
    ],
  },
  {
    name: 'Bar Muscle-Up',
    discipline: 'gymnastics',
    movementPattern: 'vertical_pull',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'triceps', role: 'primary' },
      { muscleId: 'biceps', role: 'secondary' },
    ],
  },
  {
    name: 'Pistol Squat',
    discipline: 'bodyweight',
    movementPattern: 'squat',
    metricShape: 'rounds_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'GHD Sit-Up',
    discipline: 'bodyweight',
    movementPattern: 'core',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'abs', role: 'primary' },
      { muscleId: 'quads', role: 'secondary' },
      { muscleId: 'hamstrings', role: 'stabilizer' },
    ],
  },
  {
    name: 'GHD Hip Extension',
    discipline: 'bodyweight',
    movementPattern: 'hinge',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'erectors', role: 'secondary' },
    ],
  },
  {
    name: 'Ring Row',
    discipline: 'gymnastics',
    movementPattern: 'horizontal_pull',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ENDURANCE — CARDIO (distance_time or duration)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Run',
    discipline: 'cardio',
    movementPattern: 'gait',
    metricShape: 'distance_time',
    unilateral: false,
    muscles: [],
  },
  {
    name: 'Treadmill Run',
    discipline: 'cardio',
    movementPattern: 'gait',
    metricShape: 'distance_time',
    unilateral: false,
    muscles: [],
  },
  {
    name: 'Trail Run',
    discipline: 'cardio',
    movementPattern: 'gait',
    metricShape: 'distance_time',
    unilateral: false,
    muscles: [],
  },
  {
    name: 'Rowing (Erg)',
    discipline: 'cardio',
    movementPattern: 'horizontal_pull',
    metricShape: 'distance_time',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'glutes', role: 'secondary' },
    ],
  },
  {
    name: 'Bike (Erg)',
    discipline: 'cardio',
    movementPattern: 'gait',
    metricShape: 'distance_time',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'secondary' },
      { muscleId: 'glutes', role: 'secondary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },
  {
    name: 'Road Bike',
    discipline: 'cardio',
    movementPattern: 'gait',
    metricShape: 'distance_time',
    unilateral: false,
    muscles: [],
  },
  {
    name: 'Ski Erg',
    discipline: 'cardio',
    movementPattern: 'vertical_pull',
    metricShape: 'distance_time',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'abs', role: 'secondary' },
    ],
  },
  {
    name: 'Swim',
    discipline: 'cardio',
    movementPattern: 'horizontal_pull',
    metricShape: 'distance_time',
    unilateral: false,
    muscles: [],
  },
  {
    name: 'Jump Rope',
    discipline: 'cardio',
    movementPattern: 'gait',
    metricShape: 'duration',
    unilateral: false,
    muscles: [
      { muscleId: 'calves', role: 'secondary' },
    ],
  },
  {
    name: 'Double-Under',
    discipline: 'cardio',
    movementPattern: 'gait',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'calves', role: 'secondary' },
      { muscleId: 'forearms', role: 'secondary' },
    ],
  },
  {
    name: 'Assault Bike',
    discipline: 'cardio',
    movementPattern: 'gait',
    metricShape: 'distance_time',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'secondary' },
      { muscleId: 'glutes', role: 'secondary' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // CLASS / CONDITIONING (duration, empty or minimal muscle maps)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'F45 Class',
    discipline: 'cardio',
    movementPattern: 'other',
    metricShape: 'duration',
    unilateral: false,
    muscles: [],
  },
  {
    name: 'HIIT Circuit',
    discipline: 'cardio',
    movementPattern: 'other',
    metricShape: 'duration',
    unilateral: false,
    muscles: [],
  },
  {
    name: 'Spin Class',
    discipline: 'cardio',
    movementPattern: 'gait',
    metricShape: 'duration',
    unilateral: false,
    muscles: [],
  },
  {
    name: 'CrossFit WOD',
    discipline: 'cardio',
    movementPattern: 'other',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [],
  },
  {
    name: 'Yoga',
    discipline: 'bodyweight',
    movementPattern: 'other',
    metricShape: 'duration',
    unilateral: false,
    muscles: [],
  },
  {
    name: 'Mobility Session',
    discipline: 'bodyweight',
    movementPattern: 'other',
    metricShape: 'duration',
    unilateral: false,
    muscles: [],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ADDITIONAL STRENGTH — filling out to ~150 total
  // ─────────────────────────────────────────────────────────────────────────

  // Kettlebell extra
  {
    name: 'Kettlebell Press',
    discipline: 'kettlebell',
    movementPattern: 'vertical_push',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Kettlebell Turkish Get-Up',
    discipline: 'kettlebell',
    movementPattern: 'other',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'abs', role: 'primary' },
      { muscleId: 'obliques', role: 'primary' },
      { muscleId: 'glutes', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'triceps', role: 'stabilizer' },
    ],
  },
  {
    name: 'Kettlebell Goblet Squat',
    discipline: 'kettlebell',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Kettlebell Row',
    discipline: 'kettlebell',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
    ],
  },
  {
    name: 'Kettlebell Deadlift',
    discipline: 'kettlebell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'erectors', role: 'secondary' },
    ],
  },
  {
    name: 'Double Kettlebell Front Squat',
    discipline: 'kettlebell',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'delts', role: 'stabilizer' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },

  // Extra barbell movements
  {
    name: 'Barbell Hip Thrust',
    discipline: 'barbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Barbell Row',
    discipline: 'barbell',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
    ],
  },
  {
    name: 'EZ-Bar Curl',
    discipline: 'barbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'biceps', role: 'primary' },
      { muscleId: 'forearms', role: 'secondary' },
    ],
  },
  {
    name: 'Deficit Deadlift',
    discipline: 'barbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'erectors', role: 'primary' },
      { muscleId: 'quads', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Trap Bar Deadlift',
    discipline: 'barbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'erectors', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Zercher Squat',
    discipline: 'barbell',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
      { muscleId: 'biceps', role: 'stabilizer' },
    ],
  },

  // Extra cable & machine
  {
    name: 'Cable Pull-Through',
    discipline: 'cable',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'erectors', role: 'secondary' },
    ],
  },
  {
    name: 'Cable Fly (High)',
    discipline: 'cable',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Cable Fly (Low)',
    discipline: 'cable',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Pec Deck',
    discipline: 'machine',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Hip Abduction Machine',
    discipline: 'machine',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
    ],
  },
  {
    name: 'Hip Adduction Machine',
    discipline: 'machine',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
    ],
  },
  {
    name: 'Seated Row Machine',
    discipline: 'machine',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
    ],
  },

  // Extra dumbbell
  {
    name: 'Dumbbell Pullover',
    discipline: 'dumbbell',
    movementPattern: 'vertical_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'chest', role: 'secondary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },
  {
    name: 'Dumbbell Shoulder Shrug',
    discipline: 'dumbbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'traps', role: 'primary' },
    ],
  },
  {
    name: 'Dumbbell Hip Thrust',
    discipline: 'dumbbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },
  {
    name: 'Incline Dumbbell Curl',
    discipline: 'dumbbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'biceps', role: 'primary' },
    ],
  },
  {
    name: 'Concentration Curl',
    discipline: 'dumbbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'biceps', role: 'primary' },
    ],
  },

  // Bodyweight extra
  {
    name: 'Diamond Push-Up',
    discipline: 'bodyweight',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'triceps', role: 'primary' },
      { muscleId: 'chest', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Pike Push-Up',
    discipline: 'bodyweight',
    movementPattern: 'vertical_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },
  {
    name: 'Nordic Curl',
    discipline: 'bodyweight',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'glutes', role: 'stabilizer' },
    ],
  },
  {
    name: 'Glute Bridge',
    discipline: 'bodyweight',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },
  {
    name: 'Single-Leg Glute Bridge',
    discipline: 'bodyweight',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Hollow Body Hold',
    discipline: 'bodyweight',
    movementPattern: 'core',
    metricShape: 'duration',
    unilateral: false,
    muscles: [
      { muscleId: 'abs', role: 'primary' },
      { muscleId: 'obliques', role: 'secondary' },
    ],
  },
  {
    name: 'L-Sit',
    discipline: 'gymnastics',
    movementPattern: 'core',
    metricShape: 'duration',
    unilateral: false,
    muscles: [
      { muscleId: 'abs', role: 'primary' },
      { muscleId: 'quads', role: 'secondary' },
      { muscleId: 'triceps', role: 'stabilizer' },
    ],
  },

  // CrossFit-specific conditioning
  {
    name: 'Sandbag Clean',
    discipline: 'bodyweight',
    movementPattern: 'olympic',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Med Ball Clean',
    discipline: 'bodyweight',
    movementPattern: 'olympic',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
    ],
  },
  {
    name: 'Rope Climb',
    discipline: 'gymnastics',
    movementPattern: 'vertical_pull',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'biceps', role: 'primary' },
      { muscleId: 'forearms', role: 'primary' },
      { muscleId: 'abs', role: 'secondary' },
    ],
  },
  {
    name: 'Devil Press',
    discipline: 'dumbbell',
    movementPattern: 'other',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'abs', role: 'secondary' },
    ],
  },
  {
    name: 'Sled Push',
    discipline: 'bodyweight',
    movementPattern: 'carry',
    metricShape: 'distance_time',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'calves', role: 'secondary' },
    ],
  },
  {
    name: 'Sled Pull',
    discipline: 'bodyweight',
    movementPattern: 'carry',
    metricShape: 'distance_time',
    unilateral: false,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'lats', role: 'secondary' },
      { muscleId: 'traps', role: 'secondary' },
    ],
  },
  {
    name: 'Battle Ropes',
    discipline: 'cardio',
    movementPattern: 'other',
    metricShape: 'duration',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'abs', role: 'secondary' },
      { muscleId: 'forearms', role: 'secondary' },
    ],
  },
  {
    name: 'Sumo Deadlift High Pull',
    discipline: 'barbell',
    movementPattern: 'olympic',
    metricShape: 'rounds_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Push Press',
    discipline: 'barbell',
    movementPattern: 'vertical_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'quads', role: 'secondary' },
      { muscleId: 'glutes', role: 'secondary' },
    ],
  },
  {
    name: 'Dumbbell Snatch',
    discipline: 'dumbbell',
    movementPattern: 'olympic',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'traps', role: 'secondary' },
    ],
  },

  // Machine & cable extras
  {
    name: 'Smith Machine Squat',
    discipline: 'machine',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },
  {
    name: 'Smith Machine Bench Press',
    discipline: 'machine',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'triceps', role: 'secondary' },
    ],
  },
  {
    name: 'Cable Upright Row',
    discipline: 'cable',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'biceps', role: 'secondary' },
    ],
  },
  {
    name: 'Barbell Upright Row',
    discipline: 'barbell',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'biceps', role: 'secondary' },
    ],
  },
  {
    name: 'Cable Tricep Extension (Overhead)',
    discipline: 'cable',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'triceps', role: 'primary' },
    ],
  },
  {
    name: 'Seated Dumbbell Curl',
    discipline: 'dumbbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: true,
    muscles: [
      { muscleId: 'biceps', role: 'primary' },
      { muscleId: 'forearms', role: 'secondary' },
    ],
  },
  {
    name: 'Wrist Curl',
    discipline: 'dumbbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'forearms', role: 'primary' },
    ],
  },
  {
    name: 'Calf Press on Leg Press',
    discipline: 'machine',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    muscles: [
      { muscleId: 'calves', role: 'primary' },
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────
  // BATCH 2 (migration 0014) — catalog top-up, 2026-07 feature batch.
  // Rows carry seedBatch: 2 so the generator emits them into
  // 0014_seed_catalog_2.sql instead of rewriting the shipped 0002.
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'T-Bar Row',
    discipline: 'machine',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
      { muscleId: 'erectors', role: 'stabilizer' },
    ],
  },
  {
    name: 'Meadows Row',
    discipline: 'barbell',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: true,
    seedBatch: 2,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Seal Row',
    discipline: 'barbell',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'traps', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
    ],
  },
  {
    name: 'Kroc Row',
    discipline: 'dumbbell',
    movementPattern: 'horizontal_pull',
    metricShape: 'load_reps',
    unilateral: true,
    seedBatch: 2,
    muscles: [
      { muscleId: 'lats', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'biceps', role: 'secondary' },
      { muscleId: 'forearms', role: 'secondary' },
    ],
  },
  {
    name: 'Landmine Press',
    discipline: 'barbell',
    movementPattern: 'vertical_push',
    metricShape: 'load_reps',
    unilateral: true,
    seedBatch: 2,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'chest', role: 'secondary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Belt Squat',
    discipline: 'machine',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },
  {
    name: 'Sissy Squat',
    discipline: 'bodyweight',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Pause Squat',
    discipline: 'barbell',
    movementPattern: 'squat',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'erectors', role: 'stabilizer' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Reverse Hyperextension',
    discipline: 'machine',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'erectors', role: 'secondary' },
    ],
  },
  {
    name: 'Back Extension',
    discipline: 'bodyweight',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'erectors', role: 'primary' },
      { muscleId: 'glutes', role: 'secondary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },
  {
    name: 'Snatch-Grip Deadlift',
    discipline: 'barbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'erectors', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
      { muscleId: 'lats', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Jefferson Deadlift',
    discipline: 'barbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'quads', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
      { muscleId: 'erectors', role: 'secondary' },
      { muscleId: 'obliques', role: 'stabilizer' },
    ],
  },
  {
    name: 'B-Stance Romanian Deadlift',
    discipline: 'barbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: true,
    seedBatch: 2,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'erectors', role: 'stabilizer' },
    ],
  },
  {
    name: 'B-Stance Hip Thrust',
    discipline: 'barbell',
    movementPattern: 'hinge',
    metricShape: 'load_reps',
    unilateral: true,
    seedBatch: 2,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'hamstrings', role: 'secondary' },
    ],
  },
  {
    name: 'Floor Press',
    discipline: 'barbell',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'triceps', role: 'primary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Close-Grip Bench Press',
    discipline: 'barbell',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'triceps', role: 'primary' },
      { muscleId: 'chest', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Larsen Press',
    discipline: 'barbell',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Spoto Press',
    discipline: 'barbell',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'triceps', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Board Press',
    discipline: 'barbell',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'triceps', role: 'primary' },
      { muscleId: 'chest', role: 'secondary' },
      { muscleId: 'delts', role: 'secondary' },
    ],
  },
  {
    name: 'Cable Crossover',
    discipline: 'cable',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'chest', role: 'primary' },
      { muscleId: 'delts', role: 'stabilizer' },
    ],
  },
  {
    name: 'JM Press',
    discipline: 'barbell',
    movementPattern: 'horizontal_push',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'triceps', role: 'primary' },
      { muscleId: 'chest', role: 'secondary' },
      { muscleId: 'delts', role: 'stabilizer' },
    ],
  },
  {
    name: 'Rope Pushdown',
    discipline: 'cable',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [{ muscleId: 'triceps', role: 'primary' }],
  },
  {
    name: 'Single-Arm Cable Pushdown',
    discipline: 'cable',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: true,
    seedBatch: 2,
    muscles: [{ muscleId: 'triceps', role: 'primary' }],
  },
  {
    name: 'Drag Curl',
    discipline: 'barbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'biceps', role: 'primary' },
      { muscleId: 'forearms', role: 'secondary' },
    ],
  },
  {
    name: 'Reverse Curl',
    discipline: 'barbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'forearms', role: 'primary' },
      { muscleId: 'biceps', role: 'secondary' },
    ],
  },
  {
    name: 'Bayesian Curl',
    discipline: 'cable',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: true,
    seedBatch: 2,
    muscles: [
      { muscleId: 'biceps', role: 'primary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
  {
    name: 'Y-Raise',
    discipline: 'dumbbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
    ],
  },
  {
    name: 'Powell Raise',
    discipline: 'dumbbell',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: true,
    seedBatch: 2,
    muscles: [
      { muscleId: 'delts', role: 'primary' },
      { muscleId: 'traps', role: 'secondary' },
    ],
  },
  {
    name: 'Seated Leg Curl',
    discipline: 'machine',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [{ muscleId: 'hamstrings', role: 'primary' }],
  },
  {
    name: 'Lying Leg Curl',
    discipline: 'machine',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'hamstrings', role: 'primary' },
      { muscleId: 'calves', role: 'stabilizer' },
    ],
  },
  {
    name: 'Tibialis Raise',
    discipline: 'bodyweight',
    movementPattern: 'isolation',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    // Taxonomy has no tibialis muscle — calves is the closest lower-leg
    // bucket, marked primary to satisfy the has-a-primary invariant.
    muscles: [{ muscleId: 'calves', role: 'primary' }],
  },
  {
    name: 'Copenhagen Plank',
    discipline: 'bodyweight',
    movementPattern: 'core',
    metricShape: 'duration',
    unilateral: true,
    seedBatch: 2,
    muscles: [
      { muscleId: 'glutes', role: 'primary' },
      { muscleId: 'obliques', role: 'secondary' },
      { muscleId: 'abs', role: 'stabilizer' },
    ],
  },
  {
    name: 'Dragon Flag',
    discipline: 'bodyweight',
    movementPattern: 'core',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'abs', role: 'primary' },
      { muscleId: 'obliques', role: 'secondary' },
      { muscleId: 'lats', role: 'stabilizer' },
    ],
  },
  {
    name: 'Hanging Leg Raise',
    discipline: 'bodyweight',
    movementPattern: 'core',
    metricShape: 'load_reps',
    unilateral: false,
    seedBatch: 2,
    muscles: [
      { muscleId: 'abs', role: 'primary' },
      { muscleId: 'obliques', role: 'secondary' },
      { muscleId: 'forearms', role: 'stabilizer' },
    ],
  },
]
