/**
 * Seed catalog generator — emits the seed-catalog migrations from
 * seed/catalog.ts, partitioned by each row's `seedBatch`:
 *   batch 1 (default) → migrations/0002_seed_catalog.sql   (shipped — must
 *                        regenerate byte-identical)
 *   batch 2           → migrations/0014_seed_catalog_2.sql (exercises +
 *                        exercise_muscles only; the muscle taxonomy already
 *                        exists from 0002)
 *
 * Run: npx tsx seed/generate.ts   (from packages/fitness-db/)
 *   or: npm run fitness:db:seed:gen (from repo root)
 *
 * This is a build-time CLI; console output is its progress report.
 */
/* eslint-disable no-console */

import { writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { MUSCLE_GROUPS, MUSCLES } from '@rallypoint/fitness-shared'
import { seedExerciseSchema } from '@rallypoint/fitness-shared'
import { SEED_EXERCISES } from './catalog.js'

const __dirname = dirname(fileURLToPath(import.meta.url))

// ─── Stable deterministic ID ─────────────────────────────────────────────────
// fx_seed_ + name lowercased, every run of non-alphanumeric chars replaced by
// single underscore, leading/trailing underscores removed.
function stableId(name: string): string {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
  return `fx_seed_${slug}`
}

// ─── SQL escape helpers ───────────────────────────────────────────────────────
function esc(s: string): string {
  return s.replace(/'/g, "''")
}

function sqStr(s: string): string {
  return `'${esc(s)}'`
}

// ─── Validate every row ───────────────────────────────────────────────────────
console.log(`Validating ${SEED_EXERCISES.length} seed exercises…`)

const validated = SEED_EXERCISES.map((raw, idx) => {
  const result = seedExerciseSchema.safeParse(raw)
  if (!result.success) {
    throw new Error(
      `Row ${idx} ("${raw.name}") failed validation:\n${result.error.message}`,
    )
  }
  return result.data
})

// ─── Assert no duplicate ids or names ────────────────────────────────────────
const seenIds = new Set<string>()
const seenNames = new Set<string>()

for (const ex of validated) {
  const id = stableId(ex.name)
  const nameLower = ex.name.trim().toLowerCase()

  if (seenIds.has(id)) {
    throw new Error(`Duplicate stable id: ${id} (from name "${ex.name}")`)
  }
  if (seenNames.has(nameLower)) {
    throw new Error(`Duplicate name (case-insensitive): "${ex.name}"`)
  }
  seenIds.add(id)
  seenNames.add(nameLower)
}

// ─── Partition by seed batch, sort each deterministically by id ─────────────
const batch1 = validated.filter((ex) => (ex.seedBatch ?? 1) === 1)
const batch2 = validated.filter((ex) => ex.seedBatch === 2)
const sortById = (list: typeof validated) =>
  [...list].sort((a, b) => stableId(a.name).localeCompare(stableId(b.name)))
const sorted = sortById(batch1)
const sorted2 = sortById(batch2)

function exerciseInsert(ex: (typeof validated)[number]): string {
  const id = stableId(ex.name)
  const unilateral = ex.unilateral ? 1 : 0
  return `INSERT OR IGNORE INTO exercises (id, name, owner_user_id, discipline, movement_pattern, metric_shape, unilateral, created_at, updated_at) VALUES (${sqStr(id)}, ${sqStr(ex.name)}, NULL, ${sqStr(ex.discipline)}, ${sqStr(ex.movementPattern)}, ${sqStr(ex.metricShape)}, ${unilateral}, (unixepoch()*1000), (unixepoch()*1000));`
}

function muscleInserts(ex: (typeof validated)[number]): string[] {
  const exerciseId = stableId(ex.name)
  const out: string[] = []
  const muscleSorted = [...ex.muscles].sort((a, b) => a.muscleId.localeCompare(b.muscleId))
  for (const m of muscleSorted) {
    out.push(
      `INSERT OR IGNORE INTO exercise_muscles (exercise_id, muscle_id, role) VALUES (${sqStr(exerciseId)}, ${sqStr(m.muscleId)}, ${sqStr(m.role)});`,
    )
    out.push('--> statement-breakpoint')
  }
  return out
}

// ─── Build SQL — batch 1 (0002, shipped: must regenerate byte-identical) ────
const lines: string[] = []

lines.push('-- Seed: global exercise catalog (curated)')
lines.push('-- Generated by packages/fitness-db/seed/generate.ts — do not edit by hand.')
lines.push('-- Re-run: npm run fitness:db:seed:gen')
lines.push('')

// 1. muscle_groups
const groupsSorted = [...MUSCLE_GROUPS].sort((a, b) => a.id.localeCompare(b.id))
for (const g of groupsSorted) {
  lines.push(
    `INSERT OR IGNORE INTO muscle_groups (id, name, sort) VALUES (${sqStr(g.id)}, ${sqStr(g.name)}, ${g.sort});`,
  )
  lines.push('--> statement-breakpoint')
}

// 2. muscles
const musclesSorted = [...MUSCLES].sort((a, b) => a.id.localeCompare(b.id))
for (const m of musclesSorted) {
  lines.push(
    `INSERT OR IGNORE INTO muscles (id, group_id, name, sort) VALUES (${sqStr(m.id)}, ${sqStr(m.groupId)}, ${sqStr(m.name)}, ${m.sort});`,
  )
  lines.push('--> statement-breakpoint')
}

// 3. exercises
for (const ex of sorted) {
  lines.push(exerciseInsert(ex))
  lines.push('--> statement-breakpoint')
}

// 4. exercise_muscles
for (const ex of sorted) {
  lines.push(...muscleInserts(ex))
}

const sql = lines.join('\n')

// ─── Build SQL — batch 2 (0014 top-up: exercises + muscles map only) ────────
const lines2: string[] = []
lines2.push('-- Seed: global exercise catalog top-up (batch 2, 2026-07 feature batch).')
lines2.push('-- Generated by packages/fitness-db/seed/generate.ts — do not edit by hand.')
lines2.push('-- Re-run: npm run fitness:db:seed:gen')
lines2.push('-- Additive and backward-compatible: inserts only, no DDL (same shape as 0012).')
lines2.push('')
for (const ex of sorted2) {
  lines2.push(exerciseInsert(ex))
  lines2.push('--> statement-breakpoint')
}
for (const ex of sorted2) {
  lines2.push(...muscleInserts(ex))
}
const sql2 = lines2.join('\n')

// ─── Write output ─────────────────────────────────────────────────────────────
const outPath = join(__dirname, '..', 'migrations', '0002_seed_catalog.sql')
writeFileSync(outPath, sql, 'utf8')
const outPath2 = join(__dirname, '..', 'migrations', '0014_seed_catalog_2.sql')
writeFileSync(outPath2, sql2, 'utf8')

console.log(`Wrote ${outPath}`)
console.log(`  ${MUSCLE_GROUPS.length} muscle groups`)
console.log(`  ${MUSCLES.length} muscles`)
console.log(`  ${sorted.length} exercises (batch 1)`)
const totalMuscleRows = sorted.reduce((sum, ex) => sum + ex.muscles.length, 0)
console.log(`  ${totalMuscleRows} exercise_muscle rows (batch 1)`)
console.log(`Wrote ${outPath2}`)
console.log(`  ${sorted2.length} exercises (batch 2)`)
const totalMuscleRows2 = sorted2.reduce((sum, ex) => sum + ex.muscles.length, 0)
console.log(`  ${totalMuscleRows2} exercise_muscle rows (batch 2)`)
